spring:
  application:
    name: contribute-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/Contribute?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Hemanth@2000}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:eureka-0}
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
    service-url:
      #       defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
      #      defaultZone: http://localhost:8761
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}