apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  # namespace: jenkins
spec:
  ingressClassName: nginx
  rules:
    - host: demo.backend.me
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: api-gateway-app
                port:
                  number: 80
