apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  # namespace: jenkins
spec:
  defaultBackend:
    service:
      name: default-http-backend
      # namespace: default
      port:
        number: 80
  ingressClassName: nginx
  rules:
    - host: demo.localdev.me
      http:
        paths:
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 3000
