apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  # namespace: jenkins
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
