apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
  # namespace: jenkins
data:
  eureka_service_address: http://eureka-0.eureka:8761/eureka

---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  # namespace: jenkins
  labels:
    app: eureka
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
    - port: 8761
      name: eureka

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  # namespace: jenkins
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: saihemanth1997/service-registry:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  # namespace: jenkins
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8761
